server:
  port: 8282
#spring:
#  security:
#    user:
#      name: Hasini
#      password: Hasini1234
#      roles: ADMIN, USER
#security:
#  oauth2:
#    client:
#      client-id: moblie
#      client-secret: pin
#      access-token-validity-seconds: 3600
#      authorized-grant-types: refresh-token, authorization-code, password, client-credidentials
#      scope: READ, WRITE
#    authorization:
#      check-token-access: permitAll


