server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HasiniSandunika/vehicle-config-store
          #profile service: https://github.com/krish/microservices-course-on-youtube-config-store
          #vehicle service: https://github.com/HasiniSandunika/vehicle-config-store
          search-paths:
            - 'service-config/*service'



